# Site settings
title: SPEL
subtitle: Space and Planetary Exploration Laboratory
description: >
  Space and Planetary Exploration Laboratory (SPEL) was built in 2011 in the Electrical Engineering Department of the
  University of Chile to serve as the headquarters of the design, construction, development and operation of the first
  Chilean nanosatellite, SUCHAI. Since that year, many students have contributed to the SUCHAI project and others,
  extending the areas of the laboratory.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
email: spel@ing.uchile.cl
logo: img/logos/spel.svg
header-image:
   image: img/bg-astronaut.jpg
   attrib: Photo by Niketh Vellanki on Unsplash

# Build settings
markdown: kramdown

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 636b70
  secondary: d42e12
  secondary-dark: d42e12

# Social
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/spel
  - title: envelope
    url: mailto:spel@ing.uchile.cl
  - title: github
    url: https://github.com/spel-uchile/


# Custom settings
# Uses font awesome icons name, without 'fa-' prefix. Examples:
#  space-shuttle user-astronaut globe-americas satellite meteor satellite-dish
# Use '>' after description:, so Jekyll will ignore the line breaks.
research:
  - name: Space physics and space weather
    icon: space-shuttle
    description: >
      Our Sun is not only a source of light but also the source of a solar wind. The Earth’s magnetic field shields it
      from such plasma flow, creating the magnetosphere similar to a turbulent wake behind an obstacle. Numerous
      satellites have provided invaluable information about space plasmas, allowing us to understand the extreme
      processes occurring in the near space, such as geomagnetic storms and sub-storms, which threaten human operations
      both in space and on ground.

  - name: Instrumentation and satellite communications
    icon: satellite-dish
    description: >
      Chile has unique conditions for space exploration and astronomy. We expect to keep contributing to this field in
      three lines: techniques and technologies to keep clean skies for astronomical observations; astronomical
      instruments for use in space; and space and planetary physics for stellar and exoplanetary systems

  - name: Nanosatellites
    icon: satellite
    description: >
      Engineering is key to achieve the scientific goals. We will develop Life in Extreme Environment Labs (LEEL) to
      evaluate technology to sustain life and instruments to gather data to find candidates for aerial and
      space missions. Leveraging from our experience in instrumentation, robotics, solar energy and mining, we will
      focus on its development, transportation, deployment, maintenance and efficiency in space.

partners:
  - name: Universidad de Chile
    short:  UCH
    logo: uchile.png
    url: https://uchile.cl

  - name: Universidad de Santiago de Chile
    short:  USACH
    logo: usach.png
    url: https://usach.cl

  - name: Plasma and Nuclear Fusion Group
    short: CCHEN
    logo: cchen.png
    url: https://www.cchen.cl/

  - name: Exploration and Ore Deposit Modeling
    short: AMTC
    logo: amtc.png
    url: http://www.amtc.cl/

  - name: Fault Diagnosis & Failure Prognosis
    short: FDFP
    logo: die.png
    url: https://www.cec.uchile.cl/~morchard/

  - name: Millimeter Wave Laboratory
    short: MWL
    logo: calan.jpg
    url: http://www.das.uchile.cl/lab_mwl/

  - name: Photonic Laboratory
    short: PHOTONICS
    logo: photonics.jpg
    url: http://www.raig.uchile.cl/grupos/photonics

  - name: Laboratory of Mechanical Vibrations and Rotordynamics
    short: LMVR
    logo: lvmr.png
    url: http://www.lvmr.cl/

  - name: Wireless Networking Research Group
    short: WiNetGroup
    logo: winet.png
    url: http://winetgroup.die.cl/

  - name: Laboratory for Space Weather
    short:
    logo: spaceweather.gif
    url: https://ccc.ciencias.uchile.cl/climaespacial/index.php

#  - name: Molecular electronics Laboratory
#    short:
#    logo:
#    url:

  - name: Intelligent Software Construction Laboratory
    short: ISCLab
    logo: iscl.png
    url: https://isclab.dcc.uchile.cl/

  - name: Agencia Nacional de Investigación y Desarrollo
    short: ANID
    logo: anid.png
    url: https://www.anid.cl/

  - name: Facultad de Ciencias Fisicas y Matematicas
    short: FCFM
    logo: fcfm.png
    url: http://ingenieria.uchile.cl/

satellites:
  - name: SUCHAI 1
    about: >
      First Chilean made CubeSat developed by students at the University of Chile and launched into space in June 2017.
      Its goal was to study the ionosphere.
    img: suchai1.jpg
    url:

  - name: SUCHAI 2 & 3
    about: >
      Two 3U CubeSats to study ionosphere, magnetosphere and light pollution over the north of Chile.
    img: suchai2.jpg
    url:

  - name: PlantSat
    about: >
      Its goal is to study in low earth orbit the growth of a suitable plant, replicating the conditions that life will
      experience on Mars’ surface.
    img: plantsat.jpg
    url: https://plantsat.spel.cl/

projects:
  - name: Low Cost Reaction Wheel
    about: >
      For this project a recycled BLDC motor from old HDD was used for which an optimal shape and sized flywheel
      was develop. DRV10987 driver is used for speed control. Actual Engineering Model integrated as 3axis PC104 Std.
      PCB using I2C for communication.
    img: reactionwheel.jpg
    url:

  - name: SUCHAI Flight Software
    about: >
      Open source, modular and extensible nano-satellite flight software. Flight proven in the SUCHAI I CubeSat.
      Portable to FreeRTOS and GNU/Linux.
    img: flightsoftware.jpg
    url: https://github.com/spel-uchile/SUCHAI-Flight-Software

  - name: Flight software architecture
    about: >
      The satellite flight software is a complex and crucial component. As such, assessing its overall quality is
      essential to prevent unexpected behavior and failure. We employ sophisticated visualizations and fuzz testing techniques
      to ensure its internal quality and robustness.
    img: flightsoftware2.jpg
    url: https://data.spel.cl/

  - name: Low-cost localization system for a femto-satellite constellation
    about: >
      Low cost localization system that consist on using CubeSats with GPS as a reference for the femto-satellites.
      The femto-satellites estimate their position online using a Kalman filter and the TDOA of beacons sent by the
      CubeSats.
    img: femtoLoc.jpg
    url: https://github.com/spel-uchile/FOD

  - name: Variable Thrust Profile by Sequential Pulses of an Array of Solid Propellant Engines
    about: >
      Considering that the CubeSat technology can play an important role in future planetary exploration missions, the
      design of a propulsion system for the landing process of a pseudo 6U nanosatellites is formulated.
    img: thruster.jpg
    url:

  - name: Ultra-low-cost Star Tracker for Attitude Determination
    about: >
      A Star Tracker platform in which the sub-arcminutes precision can be achieved at an ultra-low-cost, filling a
      technological gap for CubeSats. This platform is based on open source astronomy software, the Raspberry Pi 3 B+,
      and its camera.
    img: star_tracker.jpg
    url: https://github.com/spel-uchile/Star_Tracker

  - name: Pypredict
    about: >
      Real-time satellite tracker and orbit propagator. This software can simulate deployments of one satellite from
      another, move forward and backward in time, show the night-day terminator, among other features. It is used as
      a simulation platform.
    img: pypredict.jpg
    url: https://github.com/spel-uchile/Pypredict

team:
  - name: Marina Stepanova
    degree: Ph.D Physics
    role: Associate professor
    img: mstepanova.jpg
    url: https://fisica.usach.cl/users/marina

  - name: Marcos Diaz
    role: Associate professor
    degree: Ph.D. Electrical Egineering
    img: mdiaz.jpg
    url: http://ingenieria.uchile.cl/facultad/cuerpo-academico/92407/ingenieria-electrica?qui_id=13058

  - name: Alexandre Bergel
    degree: Ph.D. Computer Sciences
    role: Associate professor
    img: abergel.jpg
    url: http://bergel.eu/

  - name: Marcos Orchard
    degree: Ph.D. Electrical and Computer Engineering
    role: Associate professor
    img: morchard.jpg
    url: https://www.cec.uchile.cl/~morchard/

  - name: Carlos Gonzalez
    role: Ph.D. Student
    degree: Ph.D.(c) Electrical Engineering
    img: cgonzalez.jpg
    url: https://www.linkedin.com/in/carlosgonzalezcortes/?locale=en_US

  - name: Gustavo Díaz
    degree: Electrical Engineer
    role: Engineer
    img: gdiaz.jpg
    url:

  - name: Tamara Gutierrez
    degree: Computer Sciences
    role: Undergrad Student
    img: tgutierrez.jpg
    url:

  - name: Matías Vidal
    degree: Electrical Engineer
    role: Ph.D. Student
    img: mvidal.jpg
    url:

  - name: Alex Becerra
    degree: Electrical Engineer
    role: Engineer
    img: abecerra.jpg
    url:

  - name: Elias Obreque
    degree: Aerospace engineering
    role: Ph.D. Student
    img: eobreque.jpg
    url: https://www.linkedin.com/in/elias-obreque-3b1b67106/

  - name: Samuel Gutierrez
    degree: Physics Engineer
    role: Ph.D. Student
    img: sgutierrez.jpg
    url:

  - name: Camilo Rojas
    degree: Ms.C. Computer Sciences
    role: Engineer
    img: crojas.jpg
    url:

  - name: Mariana Salinas
    degree: Electrical Engineer
    role: Undergrad student
    img: msalinas.jpg
    url:
    
  - name: Rodrigo Muñoz
    degree: Electronic Engineer
    role: Ph.D. Student 
    img:
    url:

